version: "2"

services:
  backend:
    image: villasweb-backend
    ports:
      - "4000:4000"
    links:
      - database
    environment:
      - NODE_ENV=production

  database:
    image: mongo:latest
