version: "2"

services:
  backend:
    image: villas-backend
    ports:
      - "4000:4000"
    links:
      - database
    environment:
      - NODE_ENV=production

  database:
    image: mongo:3.2
    user: mongodb

  express:
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - database:mongo
